import { Authenticated, Refine } from "@refinedev/core";
import { DevtoolsPanel, DevtoolsProvider } from "@refinedev/devtools";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";

import routerProvider, {
  DocumentTitleHandler,
  NavigateToResource,
  UnsavedChangesNotifier,
} from "@refinedev/react-router";
import { BrowserRouter, Outlet, Route, Routes } from "react-router";
import "./App.css";
import { appResources } from "./constants/resources";
import { ErrorComponent } from "./components/refine-ui/layout/error-component";
import { Layout } from "./components/refine-ui/layout/layout";
import { Toaster } from "./components/refine-ui/notification/toaster";
import { useNotificationProvider } from "./components/refine-ui/notification/use-notification-provider";
import { ThemeProvider } from "./components/refine-ui/theme/theme-provider";
import { ApprovalQueueList } from "./pages/approvals";
import {
  CategoryCreate,
  CategoryEdit,
  CategoryList,
  CategoryShow,
} from "./pages/categories";
import { DashboardPage } from "./pages/dashboard";
import { DisbursementList } from "./pages/disbursements";
import { ForgotPassword } from "./pages/forgot-password";
import { Login } from "./pages/login";
import {
  PaymentCreate,
  PaymentEdit,
  PaymentList,
  PaymentShow,
} from "./pages/payments";
import { SetupCreate, SetupEdit, SetupShow } from "./pages/setup";
import { StaffCreate, StaffEdit, StaffList, StaffShow } from "./pages/staff";
import CreateUser from "./pages/users/create";
import EditUser from "./pages/users/edit";
import ListUsers from "./pages/users/list";
import ShowUser from "./pages/users/show";
import { authProvider } from "./providers/auth";
import { dataProvider } from "./providers/data";

const formatPathSegment = (value: string) =>
  value
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
    
const brandedTitle = ({
  resource,
  pathname,
  autoGeneratedTitle,
}: {
  resource?: { meta?: { label?: string } };
  pathname?: string;
  autoGeneratedTitle: string;
}) => {
  const resourceLabel =
    typeof resource?.meta?.label === "string" ? resource.meta.label.trim() : "";

  if (resourceLabel) {
    return `Encarta | ${resourceLabel}`;
  }

  if (pathname) {
    const segment = pathname
      .split("/")
      .filter(Boolean)
      .at(-1);

    if (segment) {
      return `Encarta | ${formatPathSegment(segment)}`;
    }
  }

  if (autoGeneratedTitle && autoGeneratedTitle.toLowerCase() !== "refine") {
    return `Encarta | ${autoGeneratedTitle}`;
  }

  return "Encarta | Business Management System";
};

function App() {
  return (
    <BrowserRouter>
      <RefineKbarProvider>
        <ThemeProvider>
          <DevtoolsProvider>
            <Refine
              dataProvider={dataProvider}
              authProvider={authProvider}
              notificationProvider={useNotificationProvider()}
              routerProvider={routerProvider}
              resources={appResources.map((resource) => ({
                name: resource.name,
                list: resource.list,
                create: resource.create,
                edit: resource.edit,
                show: resource.show,
                meta: {
                  label: resource.label,
                  icon: <resource.icon className="h-4 w-4" />,
                  canDelete: resource.canDelete,
                },
              }))}
              options={{
                syncWithLocation: true,
                warnWhenUnsavedChanges: true,
                projectId: "fFxMzl-ygw30s-D1GNyg",
              }}
            >
              <DocumentTitleHandler handler={brandedTitle} />
              <Routes>
                <Route
                  element={
                    <Authenticated key="guest-routes" fallback={<Outlet />}>
                      <NavigateToResource resource="dashboard" />
                    </Authenticated>
                  }
                >
                  <Route path="/login" element={<Login />} />
                  <Route path="/forgot-password" element={<ForgotPassword />} />
                </Route>
                <Route
                  element={
                    <Authenticated key="protected-routes" redirectOnFail="/login">
                      <Layout>
                        <Outlet />
                      </Layout>
                    </Authenticated>
                  }
                >
                  <Route
                    index
                    element={<NavigateToResource resource="dashboard" />}
                  />
                  <Route path="/dashboard" element={<DashboardPage />} />
                  <Route path="/staff">
                    <Route index element={<StaffList />} />
                    <Route path="create" element={<StaffCreate />} />
                    <Route path="edit/:id" element={<StaffEdit />} />
                    <Route path="show/:id" element={<StaffShow />} />
                  </Route>
                  <Route path="/categories">
                    <Route index element={<CategoryList />} />
                    <Route path="create" element={<CategoryCreate />} />
                    <Route path="edit/:id" element={<CategoryEdit />} />
                    <Route path="show/:id" element={<CategoryShow />} />
                  </Route>
                  <Route path="/payments">
                    <Route index element={<PaymentList />} />
                    <Route path="create" element={<PaymentCreate />} />
                    <Route path="edit/:id" element={<PaymentEdit />} />
                    <Route path="show/:id" element={<PaymentShow />} />
                  </Route>
                  <Route path="/setup">
                    <Route index element={<SetupShow />} />
                    <Route path="create" element={<SetupCreate />} />
                    <Route path="edit/:id" element={<SetupEdit />} />
                    <Route path="show/:id" element={<SetupShow />} />
                  </Route>
                  <Route path="/users">
                    <Route index element={<ListUsers />} />
                    <Route path="create" element={<CreateUser />} />
                    <Route path="edit/:id" element={<EditUser />} />
                    <Route path="show/:id" element={<ShowUser />} />
                  </Route>
                  <Route path="/approvals" element={<ApprovalQueueList />} />
                  <Route
                    path="/disbursements"
                    element={<DisbursementList />}
                  />
                  <Route path="*" element={<ErrorComponent />} />
                </Route>
              </Routes>

              <Toaster />
              <RefineKbar />
              <UnsavedChangesNotifier />
              <DocumentTitleHandler />
            </Refine>
            <DevtoolsPanel />
          </DevtoolsProvider>
        </ThemeProvider>
      </RefineKbarProvider>
    </BrowserRouter>
  );
}

export default App;
